name: confluence-static-site Test
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
      - run: yarn
      - run: yarn build
      - run: yarn lint
      - run: yarn format:check
      - run: yarn wdio
        env:
          TEST_ENVIRONMENT: ci
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: wdio-artifacts
          path: .tmp/
